### PR TITLE
feat: GA4 Support - Merge from forks

### PR DESCRIPTION
**Pull request by pnadolny13**
This brings support for GA4. 

- This PR simply merges the changes from the latest fork radbrt (hotglue->connorflynn->z3z1ma->radbrt) back into this repo
- The only thing I added was the "Repository History and Contributors" section of the README to describe where all these changes came from and the gitignore update to avoid checking in vs code artifacts
- I also created https://github.com/MeltanoLabs/tap-google-analytics/tree/main_deprecated_ua which should allow us to keep using the legacy UA apis if needed
- I have a follow on PR in https://github.com/MeltanoLabs/tap-google-analytics/pull/143 that cleans some stuff up and fixes tests. I wanted to keep those changes in a separate PR since this was mostly a direct copy/paste from the forks.

@edgarrmondragon @tayloramurphy I'm having trouble figuring out how to do this transition still. Including the hub changes too. Right now we have https://hub.meltano.com/extractors/tap-google-analytics that is now effectively "Google Analytics (Deprecated Universal Analytics API)". We also have https://hub.meltano.com/extractors/tap-ga4 which is all taps supporting GA4, most of which will be irrelevant once this PR merges because they were essentially detached forks of this repo.

Considerations:
- When I merge this anyone who uses https://hub.meltano.com/extractors/tap-google-analytics--meltanolabs/ and has not pinned their pip_url will have breaking changes e.g. view_id is now property_id, reports and credentials need to change, etc.
- One option is to re-label https://hub.meltano.com/extractors/tap-google-analytics to include "Universal Analytics" in the title and register this tap with an alias as one of the tap-ga4 variants on the hub with "GA4" in the title. This is probably cleanest since people would have to intentionally migrate to the new tap.
- All variants listed in https://hub.meltano.com/extractors/tap-google-analytics are now UA variants and are essentially deprecated but some people will still want to use these because their UA data is still available until July 1, 2024. We could pin that version to the main_deprecated_ua branch of this repo so any new installs still work for UA.

### CODE REVIEW

**Comment by pnadolny13** [comment]
Related to https://github.com/meltano/hub/issues/new

**Comment by edgarrmondragon** [comment]
> * One option is to re-label [hub.meltano.com/extractors/tap-google-analytics](https://hub.meltano.com/extractors/tap-google-analytics) to include "Universal Analytics" in the title and register this tap with an alias as one of the tap-ga4 variants on the hub with "GA4" in the title. This is probably cleanest since people would have to intentionally migrate to the new tap.

I like this option. Maybe we can merge this into a branch other than `main`, perhaps `ga4`?

**Comment by pnadolny13** [comment]
> I like this option. Maybe we can merge this into a branch other than main, perhaps ga4?
Yeah thats what I was leaning towards too, I created https://github.com/meltano/hub/pull/1432 that has the updates. I'm happy to do a ga4 branch and leave UA as the main branch although I dont know how we transition off that like new PRs will have to go to a non-default branch and eventually we'll want to make ga4 the main branch. How do you see all of that playing out?

**Comment by edgarrmondragon** [comment]
> I dont know how we transition off that like new PRs will have to go to a non-default branch and eventually we'll want to make ga4 the main branch. How do you see all of that playing out?

We can make `ga4` the default branch, so PRs automatically are opened against it and keep `main` as the head of the legacy UA tap so we don't break any users. So:

GA4 => `ga4`
UA => `main`

**Comment by pnadolny13** [comment]
@edgarrmondragon I actually made an assumption that a naked pip_url like `git+https://github.com/MeltanoLabs/tap-google-analytics.git` would always install the default branch so once we switch to `ga4` being the default then we'd still end up potentially breaking users projects. Right? Is there other benefits of using a new `ga4` branch that I'm missing?

**Comment by edgarrmondragon** [comment]
@pnadolny13 Ah, I thought the `pip_url` was pointing explicitly to `main` 🤦‍♂️. Sorry about the confusion.

**Review by tayloramurphy — APPROVED** [review]

**Comment by pnadolny13** [comment]
@edgarrmondragon ah ok, it makes me want to put a branch name on all git urls on the hub to save us from this in the future. Do you think I'm good to merge? I can also send out a message in slack and direct people to install the new GA4 plugin when they want to migrate.

**Review by edgarrmondragon — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon ah ok, it makes me want to put a branch name on all git urls on the hub to save us from this in the future. Do you think I'm good to merge? I can also send out a message in slack and direct people to install the new GA4 plugin when they want to migrate.

@pnadolny13 :shipit:

**Pull request merged**
